stages:
  - test
  - deploy

image: python:3.8.5

before_script:
  - export PYTHONPATH=src
  - python3 --version
  - python3 -m pip install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow_cpu-2.2.0-cp38-cp38-manylinux2010_x86_64.whl
  - python3 -m pip install --upgrade --no-binary numpy==1.19.0 numpy==1.19.0
  - pip install -r requirements.txt
  - pip uninstall -y numpy
  - pip install numpy==1.19.0

test:
  stage: test
  script:
    - ls
    - python -m unittest discover -s tests -v
  only:
    - tf2

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r docs/build/html/* .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - tf2
