# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
    exclude: 'tutorials/notebooks_starter/asp7.csv|tutorials/notebooks_starter/asp7.xtc|tutoials/notebooks_starter/Tensorboard_Images.png|tutorials/notebooks_intermediate/glu7.xtc|tests/data/1am7_corrected_with_CVs.h5|tests/data/PFFP_MD_fin_protonly.tpr|tests/data/1YUF.pdb|tests/data/tip3p_300K_1ATM.xtc|tests/data/1GHC.pdb|tests/data/1YUG.pdb|tests/data/messy_dataset.nc|weights_and_biases_m1_diUbq.npz|tutorials/docker/water_simulation/spc216_stacked.gro|tutorials/docker/water_simulation/spc216_fails.gro'
  - id: end-of-file-fixer
  - id: check-ast
    exclude: development/
  - id: check-yaml
    exclude: .github/
  - id: detect-private-key

#- repo: https://github.com/pre-commit/mirrors-mypy
#  rev: v0.910-1  # Use the sha / tag you want to point at
#  hooks:
#  - id: mypy
#    args: [--config-file pyproject.toml]

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
    - id: isort
      name: isort (python)
      args: ["--profile", "black", "--project", "encodermap", "--filter-files"]

- repo: https://github.com/psf/black
  rev: 24.2.0
  hooks:
    - id: black
      args: [--config=./pyproject.toml]

# - repo: https://github.com/jendrikseipp/vulture
#   rev: v2.3 # or any later Vulture version
#   hooks:
#     - id: vulture

- repo: https://github.com/kevinsawade/pre-commit-hooks
  rev: 0.0.6 # new pushed of my repos are available as @latest
  hooks:
    - id: clear-ipynb-cells
      additional_dependencies: ["notebook==6.4.12", "traitlets==5.9.0"]
    - id: assert-version-advance
      args: [ --branch=main, --remote=public ]
    # - id: run-pycodestyle
